red-hat-data-services/notebooks

.github/pull.yml

Configure https://github.com/wei/pull to synchronize changes from https://github.com/opendatahub-io/notebooks

Enable wei:pull GH robot

---

.github/workflows/sync-release-branch-2023a.yml

To auto sync branches from upstream to downstream without creating new token

GH: update auto sync to use aormsby/Fork-Sync-With-Upstream-action

---

.github/workflows/sync-release-branch-2023a.yml

Changed branch name to comply with the openshift-ci, and also updated the workflow to monitor to the new name

Change branch name to comply with the openshift-ci

---

jupyter/datascience/ubi8-python-3.8/Dockerfile
jupyter/datascience/ubi9-python-3.9/Dockerfile
jupyter/tensorflow/ubi8-python-3.8/Pipfile
jupyter/tensorflow/ubi8-python-3.8/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock

Sync the downstream main with the upstream

Sync downstream main with the upstream

---

.github/workflows/sync-release-branch-2023a.yml

When manual click workflow name on left side, "Run Workflow" is avaiable.

Feat: enable manual trigger GH action

---

jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json

Update the runtime image for the release branch based on commit 869b370
https://quay.io/repository/modh/runtime-images?tab=tags

Update the runtime image for release branch based on commit 869b370

---

jupyter/datascience/ubi8-python-3.8/Dockerfile
jupyter/datascience/ubi8-python-3.8/Pipfile
jupyter/datascience/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi8-python-3.8/setup-elyra.sh
jupyter/datascience/ubi9-python-3.9/Dockerfile
jupyter/datascience/ubi9-python-3.9/Pipfile
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/setup-elyra.sh
jupyter/pytorch/ubi8-python-3.8/Pipfile
jupyter/pytorch/ubi8-python-3.8/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi8-python-3.8/Pipfile
jupyter/tensorflow/ubi8-python-3.8/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock

Remove the elyra pipeline plugin with additional resource
Cherry-picked from upstream.
`git cherry-pick 7e6cc20fff20db1bbfd0037e593fe4d738d14fe3`

Remove the elyra pipeline plugin with additional resource

---

jupyter/datascience/ubi8-python-3.8/Dockerfile
jupyter/datascience/ubi8-python-3.8/setup-elyra.sh
jupyter/datascience/ubi8-python-3.8/utils/kfp_authentication.patch
jupyter/datascience/ubi8-python-3.8/utils/processor_kfp.patch
jupyter/datascience/ubi9-python-3.9/Dockerfile
jupyter/datascience/ubi9-python-3.9/setup-elyra.sh
jupyter/datascience/ubi9-python-3.9/utils/kfp_authentication.patch
jupyter/datascience/ubi9-python-3.9/utils/processor_kfp.patch

Include patch option for providing ssl_ca_certs
cherry-picked from odh/notebooks main: 74587dcbba2649d0abe6e81ebadf7b135e24df81

sync main branch with opendatahub main

---

jupyter/datascience/ubi9-python-3.9/Dockerfile
jupyter/datascience/ubi9-python-3.9/utils/processor_kfp.patch

Sync the main branch with the opendatahub notebook main
The sync contains, the following PR/commits:
- https://github.com/opendatahub-io/notebooks/commit/f30a9339bf049e30de9c1c5dbd8ba683c8c9fbc1
- https://github.com/opendatahub-io/notebooks/commit/ec50408b9a4954d40b4eb9c340ec6aaaca00c818

Sync main branch with opendatahub notebook main

---

jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json

Fix on runtime images the image_name field

Fix on runtime images the image_name field

---

jupyter/datascience/anaconda-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json

chores: Update the runtime image with the commit: 8bda2fa

chores: Update the runtime image with the commit: 8bda2fa

---

.github/workflows/notebook-digest-updater.yaml

Fix the path to the params.env file

Fix the path to the params.env file

---

manifests/base/jupyter-habana-notebook-imagestream.yaml
manifests/base/kustomization.yaml
manifests/base/params.env
manifests/base/params.yaml

Patch the imagestream by removing habana 1.11.0
Related-to: https://github.com/opendatahub-io/notebooks/issues/297

Patch the imagestream by removing habana 1.11.0

---

manifests/base/commit.env
manifests/base/params.env

sync rhoai-2.6 branch with release-2023b branch
This is for the code-freeze.

sync rhoai-2.6 branch with release-2023b branch

---

jupyter/datascience/anaconda-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json

Upgrade: Update runtime image on main based on the commit id: 0a828ae
With change of codeflare-sdk version, upgrading the runtime images as well.

Upgrade: Update runtime image on main based on the commit id: 0a828ae

---

ci/check-json.sh

Created in the downstream first as here we have the "problemmatic" yaml file. I will create PR against upstream once the review here is finalized.

[CI] Fix for the yaml files that contain multiple definitions.

---

ci/check-json.sh
cuda/rhel9-python-3.9/Dockerfile
manifests/base/cuda-rstudio-buildconfig.yaml
manifests/base/rstudio-buildconfig.yaml
rstudio/rhel9-python-3.9/Dockerfile
rstudio/rhel9-python-3.9/nginx/root/opt/app-root/nginxconf.sed

sync cherry-picked commit from main to release-2023b branch
Cherry-picked commits:
- https://github.com/red-hat-data-services/notebooks/commit/c9c35a43ee796c426fb5f54112bb84d187e6af9c
- https://github.com/red-hat-data-services/notebooks/commit/48d469242f4314be5e303868e47690812435d793
- https://github.com/red-hat-data-services/notebooks/commit/618e17c65917995ee291204ad38f0e7bee9da5b9
- https://github.com/red-hat-data-services/notebooks/commit/f5e99b62004b77dd61e7b26980eaaf5552febab1

sync cherry-picked commit from main to release-2023b branch

---

README.md
codeserver/c9s-python-3.9/nginx/root/opt/app-root/nginxconf.sed
codeserver/ubi9-python-3.9/nginx/root/opt/app-root/nginxconf.sed
docs/workbenches.md
jupyter/datascience/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi8-python-3.8/utils/processor_kfp.patch
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/utils/processor_kfp.patch
jupyter/minimal/ubi8-python-3.8/Pipfile.lock
jupyter/minimal/ubi9-python-3.9/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
rstudio/c9s-python-3.9/Dockerfile
rstudio/c9s-python-3.9/nginx/root/opt/app-root/nginxconf.sed
runtimes/datascience/ubi8-python-3.8/Pipfile.lock
runtimes/datascience/ubi9-python-3.9/Pipfile.lock
runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock

sync release-2023b branch with upstream ODH 2023b branch changes
Fixes: https://github.com/red-hat-data-services/notebooks/actions/runs/7840299561/job/21394680211
As the github action failed, completing this manually.

sync release-2023b branch with upstream ODH 2023b branch changes

---

manifests/base/cuda-rstudio-buildconfig.yaml

Related to: https://issues.redhat.com/browse/RHOAIENG-2788

hot fix: bump cuda resources

---

jupyter/datascience/anaconda-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json

Upgrade: Update runtime image on release-2023b based on the commit id d4b8703
As codeflare SDK is upgrade to version 0.14.1

Upgrade: Update runtime image on release-2023b based on the commit id d4b8703

---

jupyter/datascience/anaconda-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json

sync release-2023b branch with final commit for code-freeze 2.8
This PR includes, 
- upstream 2023b branch changes.
- Updated runtime-images for notebooks, as package nbconvert, urllib and codeflare are updated.

sync release-2023b branch with final commit for code-freeze 2.8

---

.github/workflows/sync-release-branch-2024a.yml

Related to: https://issues.redhat.com/browse/RHOAIENG-4342
Create sync workflow for the release-2024a

Create sync workflow for the release-2024a

---

habana/1.13.0/ubi8-python-3.8/Pipfile
habana/1.13.0/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi8-python-3.8/Pipfile
jupyter/datascience/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/Pipfile
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi8-python-3.8/Pipfile
jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
runtimes/datascience/ubi8-python-3.8/Pipfile
runtimes/datascience/ubi8-python-3.8/Pipfile.lock
runtimes/datascience/ubi9-python-3.9/Pipfile
runtimes/datascience/ubi9-python-3.9/Pipfile.lock
runtimes/pytorch/ubi8-python-3.8/Pipfile
runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
runtimes/pytorch/ubi9-python-3.9/Pipfile
runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
runtimes/tensorflow/ubi8-python-3.8/Pipfile
runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
runtimes/tensorflow/ubi9-python-3.9/Pipfile
runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock

[release-2024a] sync 2024a branch from upstream 2024a branch with codeflare update

[release-2024a] sync 2024a branch from upstream 2024a branch with codeflare update

---

.github/workflows/runtimes-digest-updater.yaml

Fix the runtime updater github action branch 2024a
Fixes: #206

Fix the runtime updater github action branch 2024a

---

habana/1.13.0/ubi8-python-3.8/Pipfile
habana/1.13.0/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi8-python-3.8/Pipfile
jupyter/datascience/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/Pipfile
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi8-python-3.8/Pipfile
jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock

sync release-2024a branch with upstream 2024a branch
Opened this as the PR automation failed: https://github.com/red-hat-data-services/notebooks/actions/runs/8612549561

sync release-2024a branch with upstream 2024a branch

---

habana/1.13.0/ubi8-python-3.8/Pipfile
habana/1.13.0/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi8-python-3.8/Pipfile
jupyter/datascience/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/Pipfile
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi8-python-3.8/Pipfile
jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock

[release-2024a] sync release 2024a branch with change from upstream 2024a
Automation failed: https://github.com/red-hat-data-services/notebooks/actions/runs/8622507755

[release-2024a] sync release 2024a branch with change from upstream 2024a

---

habana/1.13.0/ubi8-python-3.8/Pipfile
habana/1.13.0/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi8-python-3.8/Pipfile
jupyter/datascience/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/Pipfile
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi8-python-3.8/Pipfile
jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock

[release-2024a] sync release-2024a branch with upstream 2024a
Automation failed: https://github.com/red-hat-data-services/notebooks/actions/runs/8650993913

[release-2024a] sync release-2024a branch with upstream 2024a

---

manifests/base/cuda-rstudio-buildconfig.yaml
manifests/base/rstudio-buildconfig.yaml

Set the rstudio builds with the branch rhoai-2.10

Set the rstudio builds with the branch rhoai-2.10

---

.github/workflows/code-quality.yaml
ci/hadolint-config.yaml

(cherry picked from commit 34bafd49f32d2e818bb510ade941ab55dd1957f9)
https://issues.redhat.com/browse/RHOAIENG-7886

[CI] Add `kubectl kustomize` run to check our manifests definition

---

jupyter/datascience/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/minimal/ubi8-python-3.8/Pipfile.lock
jupyter/minimal/ubi9-python-3.9/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
runtimes/datascience/ubi8-python-3.8/Pipfile.lock
runtimes/datascience/ubi9-python-3.9/Pipfile.lock
runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock

[release-2023b] sync release-2023b branch with upstream 2023b branch
The sync github action has been failing for a while:
https://github.com/red-hat-data-services/notebooks/actions/workflows/sync-release-branch-2023b.yml

[release-2023b] sync release-2023b branch with upstream 2023b branch

---

base/rhel9-python-3.9/Dockerfile
ci/check-params-env.sh
manifests/base/kustomization.yaml
manifests/base/params.env
manifests/base/params.yaml
rstudio/rhel9-python-3.9/Dockerfile

Cherry pick #179, #253 and #254 to release-2024a
supersedes the #272
https://issues.redhat.com/browse/RHOAIENG-7884

[release-2024a] Cherry pick #179, #253 and #254 to release-2024a

---

jupyter/datascience/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/minimal/ubi8-python-3.8/Pipfile.lock
jupyter/minimal/ubi9-python-3.9/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
runtimes/datascience/ubi8-python-3.8/Pipfile.lock
runtimes/datascience/ubi9-python-3.9/Pipfile.lock
runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock

sync 2023b branch with upstream opendatahub 2023b branch
- Include all the commits from the 2023b branch

[release-2023b] sync 2023b branch with upstream opendatahub 2023b branch

---

manifests/base/cuda-rstudio-buildconfig.yaml
manifests/base/rstudio-buildconfig.yaml

feat(Rstudio): update branch rhoai-2.11 for the rstudio builds

feat(Rstudio): update branch rhoai-2.11 for the rstudio builds

---

ci/check-params-env.sh

Fixes https://github.com/red-hat-data-services/notebooks/actions/runs/10216926068/job/28269563262

[CI] remove the workaround for the Habana 1.10 image check

---

docs/workbenches.md
manifests/base/jupyter-habana-notebook-imagestream.yaml

Related to: https://issues.redhat.com/browse/RHOAIENG-13278

Remove Habana from manifests and repository docs

---

jupyter/datascience/ubi9-python-3.11/runtime-images/datascience-ubi9-py311.json
jupyter/datascience/ubi9-python-3.11/runtime-images/pytorch-ubi9-py311.json
jupyter/datascience/ubi9-python-3.11/runtime-images/rocm-pytorch-ubi9-py311.json
jupyter/datascience/ubi9-python-3.11/runtime-images/rocm-tensorflow-ubi9-py311.json
jupyter/datascience/ubi9-python-3.11/runtime-images/tensorflow-ubi9-py311.json
jupyter/datascience/ubi9-python-3.11/runtime-images/ubi9-py311.json

Sync the runtime image on the main repo for the sanity
This change in code-base doesn't have much effect in `main` branch, this change is already in 2024b branch #415 
Only bring in here, as disconnected repo changes are take look from main branch , only for sanity opening this PR.

Sync the runtime image on the main repo for the sanity

---

docs/workbenches.md
manifests/base/jupyter-habana-notebook-imagestream.yaml

Related to: https://issues.redhat.com/browse/RHOAIENG-13414 
`git cherry-pick` 8501f5c3

[RHOAI-2.10] Deactivate Habana notebook from manifests and repository docs

---

docs/workbenches.md
manifests/base/jupyter-habana-notebook-imagestream.yaml

Related to: https://issues.redhat.com/browse/RHOAIENG-13467
`git cherry-pick` 8501f5c3

[RHOAI-2.13] Deactivate Habana notebook from manifests and repository docs

---

jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json

fix conflits on runtimes images

fix conflits on runtimes images

---

ci/check-params-env.sh
ci/check-runtime-images.sh

This was created as a followup to the #515.
I can either push this extra mine commit into @andyatmiami PR branch or we can simply merge Andy's PR first and I can then rebase this one mine and merge it separately. I don't mind either way.
```
./ci/check-params-env.sh
./ci/check-runtime-images.sh
```

NO-JIRA: chore(ci): fix checks scripts for params.env and runtimes

---

ci/check-params-env.sh

* https://github.com/red-hat-data-services/notebooks/pull/899

update Image size after adding PDF Export dependencies

---

ci/check-params-env.sh

https://issues.redhat.com/browse/RHOAIENG-30247
Discussed in
* https://github.com/red-hat-data-services/notebooks/pull/1259#issuecomment-3113684090

[2.22] RHOAIENG-30247: update expected image sizes in `check-params-env.sh` for PyTorch and TrustyAI environments

---

codeserver/ubi9-python-3.11/Dockerfile.konflux.cpu
codeserver/ubi9-python-3.12/Dockerfile.konflux.cpu
jupyter/datascience/ubi9-python-3.11/Dockerfile.konflux.cpu
jupyter/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu
jupyter/minimal/ubi9-python-3.11/Dockerfile.konflux.cpu
jupyter/minimal/ubi9-python-3.11/Dockerfile.konflux.cuda
jupyter/minimal/ubi9-python-3.11/Dockerfile.konflux.rocm
jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.cpu
jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.cuda
jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.rocm
jupyter/pytorch/ubi9-python-3.11/Dockerfile.konflux.cuda
jupyter/pytorch/ubi9-python-3.12/Dockerfile.konflux.cuda
jupyter/rocm/pytorch/ubi9-python-3.11/Dockerfile.konflux.rocm
jupyter/rocm/pytorch/ubi9-python-3.12/Dockerfile.konflux.rocm
jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile.konflux.rocm
jupyter/tensorflow/ubi9-python-3.11/Dockerfile.konflux.cuda
jupyter/tensorflow/ubi9-python-3.12/Dockerfile.konflux.cuda
jupyter/trustyai/ubi9-python-3.11/Dockerfile.konflux.cpu
jupyter/trustyai/ubi9-python-3.12/Dockerfile.konflux.cpu
runtimes/datascience/ubi9-python-3.11/Dockerfile.konflux.cpu
runtimes/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu
runtimes/minimal/ubi9-python-3.11/Dockerfile.konflux.cpu
runtimes/minimal/ubi9-python-3.12/Dockerfile.konflux.cpu
runtimes/pytorch/ubi9-python-3.11/Dockerfile.konflux.cuda
runtimes/pytorch/ubi9-python-3.12/Dockerfile.konflux.cuda
runtimes/rocm-pytorch/ubi9-python-3.11/Dockerfile.konflux.rocm
runtimes/rocm-pytorch/ubi9-python-3.12/Dockerfile.konflux.rocm
runtimes/rocm-tensorflow/ubi9-python-3.11/Dockerfile.konflux.rocm
runtimes/tensorflow/ubi9-python-3.11/Dockerfile.konflux.cuda
runtimes/tensorflow/ubi9-python-3.12/Dockerfile.konflux.cuda

Ref: https://issues.redhat.com/browse/RHOAIENG-31081 
Dedicated Konflux dockefiles are required for hermetic build(phase-2) and to comply with Konflux release gates.

Add Konflux Dockerfile

---

.tekton/odh-pipeline-runtime-minimal-cpu-py311-pull-request.yaml
.tekton/odh-pipeline-runtime-minimal-cpu-py312-pull-request.yaml
.tekton/odh-workbench-jupyter-minimal-cpu-py311-pull-request.yaml
.tekton/odh-workbench-jupyter-minimal-cpu-py312-pull-request.yaml

Add s390x label for konflux build

Add s390x label for building notebook images

---

Makefile
ci/cached-builds/gen_gha_matrix_jobs.py
jupyter/minimal/ubi9-python-3.12/build-args/cpu.conf
jupyter/utils/install_pdf_deps.sh
runtimes/datascience/ubi9-python-3.12/Dockerfile.cpu
runtimes/datascience/ubi9-python-3.12/pylock.toml
runtimes/datascience/ubi9-python-3.12/pyproject.toml
scripts/generate_pull_request_pipelineruns.py

Sync downstream main from upstream main

Sync downstream main from upstream main

---

.github/workflows/build-notebooks-TEMPLATE.yaml

* https://github.com/jiridanek/notebooks/actions/runs/17496134528

[2.24] cherry-picks for test-only gha stuff that I want to see everything running to green when fixing the 2.24 blockers

---

codeserver/ubi9-python-3.11/Dockerfile.konflux.cpu
codeserver/ubi9-python-3.12/Dockerfile.konflux.cpu
jupyter/datascience/ubi9-python-3.11/Dockerfile.konflux.cpu

https://issues.redhat.com/browse/RHOAIENG-33414

[2.24] RHOAIENG-33414: remove gpg-pubkey RPMs from the datascience container images

---

runtimes/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu

Copy Dockerfile.cpu to Dockerfile.konflux.cpu

sync missing changes for runtime dsp

---

codeserver/ubi9-python-3.12/Dockerfile.konflux.cpu

* opendatahub-io/notebooks#2504
* opendatahub-io/notebooks#2512
* opendatahub-io/notebooks#2516
* opendatahub-io/notebooks#2518

RHAIENG-1247: chore(codeserver): konflux dockerfile to incorporate odh-io/notenooks changes

---

codeserver/ubi9-python-3.12/Dockerfile.konflux.cpu
jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.cpu
jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.cuda
jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.rocm
jupyter/pytorch+llmcompressor/ubi9-python-3.12/Dockerfile.konflux.cuda
jupyter/pytorch/ubi9-python-3.12/Dockerfile.konflux.cuda
jupyter/rocm/pytorch/ubi9-python-3.12/Dockerfile.konflux.rocm
jupyter/rocm/tensorflow/ubi9-python-3.12/Dockerfile.konflux.rocm
jupyter/tensorflow/ubi9-python-3.12/Dockerfile.konflux.cuda
runtimes/minimal/ubi9-python-3.12/Dockerfile.konflux.cpu
runtimes/pytorch+llmcompressor/ubi9-python-3.12/Dockerfile.konflux.cuda
runtimes/pytorch/ubi9-python-3.12/Dockerfile.konflux.cuda
runtimes/rocm-pytorch/ubi9-python-3.12/Dockerfile.konflux.rocm
runtimes/rocm-tensorflow/ubi9-python-3.12/Dockerfile.konflux.rocm
runtimes/tensorflow/ubi9-python-3.12/Dockerfile.konflux.cuda

sync rhoai-2.25 Dockerfile.konflux files with changes

---

codeserver/ubi9-python-3.12/Dockerfile.konflux.cpu
manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
manifests/base/jupyter-tensorflow-notebook-imagestream.yaml

[2.25.0] fix py version on the imagestreams

---

codeserver/ubi9-python-3.12/Dockerfile.cpu
codeserver/ubi9-python-3.12/Dockerfile.konflux.cpu
codeserver/ubi9-python-3.12/devel_env_setup.sh

Related to: https://issues.redhat.com/browse/RHAIENG-1238

RHAIENG-1238: remove EPEL from final image
