.github/pull.yml

Removed wei bot automation from the main, because we don't want always to pull all the commits for the upstream main.

Remove wei bot

---

.github/workflows/sync-release-branch-2023a.yml

Fix syntax which not replace variable in job title,
See (from origin action run) :

GitHub: fix variable name

---

jupyter/datascience/anaconda-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json

Upgrade the runtime images with rhods runtime,ref:b7e647e
The runtime image are updated with RHODS based image from quay.io/modh.
Commit reference: https://github.com/red-hat-data-services/notebooks/commit/b7e647edd3e637e7d22f4a3ef0200d128c87d296
Tags:
- runtime-cuda-tensorflow-ubi9-python-3.9-2023a-20230817-b7e647e 
- runtime-cuda-tensorflow-ubi8-python-3.8-2023a-20230817-b7e647e 
- runtime-pytorch-ubi9-python-3.9-2023a-20230817-b7e647e
- runtime-pytorch-ubi8-python-3.8-2023a-20230817-b7e647e 
- runtime-datascience-ubi8-python-3.8-2023a-20230817-b7e647e
- runtime-datascience-ubi9-python-3.9-2023a-20230817-b7e647e 
- runtime-minimal-ubi9-python-3.9-2023a-20230817-b7e647e
- runtime-minimal-ubi8-python-3.8-2023a-20230817-b7e647e

Upgrade the runtime images with rhods runtime,ref:b7e647e

---

.github/workflows/notebook-digest-updater.yaml

Fix digest updater from failing if there are no updates on the image SHA on the params.env file 
Currently, the digest updater is failing if there are no updates to commit. Ref [link](https://github.com/red-hat-data-services/notebooks/actions/runs/6655418115)
By using the 
```
shell: bash
continue-on-error: true
```
inside the `- name: Fetch digest, and update the params.env file` procedure, allow as to continue

Fix digest updater from failing if there are no updates on the image SHA on the params.env file 

---

manifests/base/jupyter-datascience-notebook-imagestream.yaml
manifests/base/jupyter-habana-notebook-imagestream.yaml
manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
manifests/base/jupyter-minimal-notebook-imagestream.yaml
manifests/base/jupyter-pytorch-notebook-imagestream.yaml
manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
manifests/base/jupyter-trustyai-notebook-imagestream.yaml

Patch the imagestream to have the same name as in odh-manifests
https://github.com/red-hat-data-services/odh-manifests/tree/master/jupyterhub/notebook-images/overlays/additional
Fixes:
- This would fix the duplication.
as older deployments would have the same image streams.
- All fixes the annotation of the sklear-onnx and removes additional recommend: true

Patch the imagestream to have same name as in odh-manifests

---

jupyter/datascience/anaconda-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/anaconda-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json

Update the runtime image with the commit: 8bda2fa on main

Update the runtime image with the commit: 8bda2fa on main

---

base/ubi8-python-3.8/Dockerfile

Based on the update:
https://catalog.redhat.com/software/containers/ubi8/python-38/5dde9cacbed8bd164a0af24a?architecture=amd64&image=64cab6d204b5b858e24f2f62

[Release-1.2] CVE 44487: Upgrade ubi package libnghttp2 to fix http2 cve

---

base/ubi8-python-3.8/Dockerfile
base/ubi9-python-3.9/Dockerfile

Based on the update: 
- https://catalog.redhat.com/software/containers/ubi9/python-39/61a61032bfd4a5234d59629e?architecture=amd64&image=65301f5a53a51a886582fba1&container-tabs=security
- https://catalog.redhat.com/software/containers/ubi8/python-38/5dde9cacbed8bd164a0af24a?architecture=amd64&image=64cab6d204b5b858e24f2f62

[RHODS-1.34] CVE 44487: Upgrade ubi package libnghttp2 to fix http2 cve

---

base/ubi8-python-3.8/Dockerfile
base/ubi9-python-3.9/Dockerfile

Based on the update: 
- https://catalog.redhat.com/software/containers/ubi9/python-39/61a61032bfd4a5234d59629e?architecture=amd64&image=65301f5a53a51a886582fba1&container-tabs=security
- https://catalog.redhat.com/software/containers/ubi8/python-38/5dde9cacbed8bd164a0af24a?architecture=amd64&image=64cab6d204b5b858e24f2f62

[RHODS-1.32] CVE 44487: Upgrade ubi package libnghttp2 to fix http2 cve

---

base/ubi8-python-3.8/Dockerfile
base/ubi9-python-3.9/Dockerfile

Based on the update: 
- https://catalog.redhat.com/software/containers/ubi9/python-39/61a61032bfd4a5234d59629e?architecture=amd64&image=65301f5a53a51a886582fba1&container-tabs=security
- https://catalog.redhat.com/software/containers/ubi8/python-38/5dde9cacbed8bd164a0af24a?architecture=amd64&image=64cab6d204b5b858e24f2f62

[RHODS-1.33] CVE 44487: Upgrade ubi package libnghttp2 to fix http2 cve

---

base/ubi8-python-3.8/Dockerfile
base/ubi9-python-3.9/Dockerfile

Based on the update: 
- https://catalog.redhat.com/software/containers/ubi9/python-39/61a61032bfd4a5234d59629e?architecture=amd64&image=65301f5a53a51a886582fba1&container-tabs=security
- https://catalog.redhat.com/software/containers/ubi8/python-38/5dde9cacbed8bd164a0af24a?architecture=amd64&image=64cab6d204b5b858e24f2f62

[main] CVE 44487: Upgrade ubi package libnghttp2 to fix http2 cve

---

jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json

Update runtime image based on the commit id: 865fe76
As we updated the codeflare-sdk version in runtime image , we should include that bits for workbench image build.
Related-to: https://github.com/opendatahub-io/notebooks/issues/327

Update runtime image based on the commit id: 865fe76

---

jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json

Update runtime image on 2023a based on the commit id: ff23c42
Related-to: https://github.com/opendatahub-io/notebooks/issues/202

Update runtime image on 2023a based on the commit id: ff23c42

---

jupyter/datascience/ubi8-python-3.8/runtime-images/datascience-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/pytorch-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/tensorflow-ubi8-py38.json
jupyter/datascience/ubi8-python-3.8/runtime-images/ubi8-py38.json
jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json

Update runtime image on 2023b based on the commit id: c8e0724
Related-to: OAI 2.5
https://github.com/opendatahub-io/notebooks/issues/329

Update runtime image on 2023b based on the commit id: c8e0724

---

manifests/base/commit.env
manifests/base/params.env

Fix: Code Server notebook sha digest on the params.env file (rhoai-2.6)
[Quay.io](https://quay.io/repository/modh/codeserver?tab=tags)

Fix: Code Server notebook sha digest on the params.env file (rhoai-2.6)

---

manifests/base/code-server-notebook-imagestream.yaml

HotFix: Fix the typo and keep code-server case-sensitive
Refer: https://redhat-internal.slack.com/archives/C05TTTYG599/p1706184360108179?thread_ts=1706112551.862629&cid=C05TTTYG599

HotFix: Fix the typo and keep code-server case-sensitive

---

Makefile
base/rhel9-python-3.9/Dockerfile
base/rhel9-python-3.9/Pipfile
base/rhel9-python-3.9/Pipfile.lock

This PR related to: https://github.com/red-hat-data-services/notebooks/pull/118
The goal here is to reduce the build time for RStudio. It doesn't need to build every time the RHEL base.
The second part of this work is the modification on the OCP-CI to store the image on a registry, the related PR is here: https://github.com/openshift/release/pull/48110

Add rhel9 base image

---

cuda/rhel9-python-3.9/Dockerfile
rstudio/rhel9-python-3.9/Dockerfile

- Fix paths on the cuda rhel Dockerfile
- Enhance the subscription manager registration cmd [#L26](https://github.com/atheo89/notebooks/blob/fix-path/rstudio/rhel9-python-3.9/Dockerfile#L26) to utilize the base and server urls as optional
- Added unregistered instructions on the bottom on the cuda rhel Dockerfile
- Fix code static analysis issues

Final fixes on the RStudio Dockerfiles

---

manifests/base/cuda-rstudio-buildconfig.yaml
manifests/base/rstudio-buildconfig.yaml

Set the release branch rhoai-2.7 as the ref in buildconfig
Related-to: https://issues.redhat.com/browse/RHOAIENG-1478

Set the release branch rhoai-2.7 as the ref in buildconfig

---

cuda/rhel9-python-3.9/Dockerfile
manifests/base/cuda-rstudio-buildconfig.yaml
manifests/base/rstudio-buildconfig.yaml
rstudio/rhel9-python-3.9/Dockerfile

This fix ensure that the credentials of the subscription manager are not revealed on while the build logs.
This way is documented here: [ocp-doc](https://docs.openshift.com/container-platform/4.10/cicd/builds/build-strategies.html#builds-using-build-volumes_build-strategies-docker)

Mount the secret on the buildConfig instead of using ENVs to avoid their exposure on the logs

---

manifests/base/cuda-rstudio-buildconfig.yaml
manifests/base/rstudio-buildconfig.yaml

Increased resources to avoid Out of Memory issue while building, especially for the CUDA ones. 
`The node was low on resource: ephemeral-storage. Container docker-build was using 6574308Ki, which exceeds its request of 0.`

Fix: Increase resources on R Studio BuildConfigs

---

manifests/base/cuda-rstudio-buildconfig.yaml
manifests/base/rstudio-buildconfig.yaml
rstudio/rhel9-python-3.9/Dockerfile
rstudio/rhel9-python-3.9/nginx/root/opt/app-root/nginxconf.sed

This Pull Request attends to change the name of R Studio to R Studio Server in all possible changes where applicable.
Note: It doesn't include changes on the rest files since will flow in downstream through the upstream PR https://github.com/opendatahub-io/notebooks/pull/407

Fix naming for RStudio Server on rhel flavor

---

rstudio/rhel9-python-3.9/Dockerfile

Adding Preinstall packages on R Studio workbench
Changes are made to the rhel9 folder.
extension of: https://github.com/opendatahub-io/notebooks/pull/386

Remove the R-package install from workbench

---

rstudio/rhel9-python-3.9/Dockerfile

Related to: https://issues.redhat.com/browse/RHOAIENG-2860

hot fix: fix user R library path version to point only the 4.3

---

manifests/base/cuda-rstudio-buildconfig.yaml
manifests/base/rstudio-buildconfig.yaml

HotFix: Remove the annotation notebook-images=true from RStudio imagestreams
Related-to: https://issues.redhat.com/browse/RHOAIENG-3008
Removed the annotation : `opendatahub.io/notebook-image: 'true'`
with this user (data scientist) wouldn't see the R studio image.
RHODS admins, could include this to imagestream once the build successful.

HotFix: Remove the annotation notebook-images=true from RStudio imagestreams

---

rstudio/rhel9-python-3.9/rsession.conf

Related to: https://github.com/red-hat-data-services/notebooks/pull/149
Missed one bit here to be totally fixed...
End to end image testing shows only one folder as expected

Fix library path version on rsession.conf file

---

base/rhel9-python-3.9/Dockerfile
rstudio/rhel9-python-3.9/Dockerfile

These changes shouldn't have any functional impact.
This fixes the CI checks and should be cherry-picked to `main`.
---
But just now, when raising this. I'm thinking whether we actually want it in the `rhoai-2.8` in the end... Please, let me know, guys.

[fix] hadolint warnings to base and rstudio Dockerfiles

---

.github/workflows/notebook-digest-updater.yaml

Related to: https://issues.redhat.com/browse/RHOAIENG-4341
This PR updates the notebooks-digest-workflow in favor 2024a release.
PS: It fixes a typo issue on  `Fetch digest, and update the commit.env file`  for N-1 release

Update digest updater workflow in favor 2024a release

---

jupyter/trustyai/ubi9-python-3.9/test/test_notebook.ipynb

I don't really understand how and why this file was broken by this commit aac06623b4942d9ceb6ea8ef5189639f4943fb1b . Our CI check notifies that something is broken in the file.
Please, review this thoroughly, I simply put back original values.
Looks like this issue isn't present in the upstream repository - https://github.com/opendatahub-io/notebooks/blob/main/jupyter/trustyai/ubi9-python-3.9/test/test_notebook.ipynb?short_path=7b4adf3.
Edit: CI passed the point of checking JSON files. The hadolint failure is gonna be fixed by #179.

Fix test file for the trustyai image

---

manifests/base/code-server-notebook-imagestream.yaml
manifests/base/commit.env
manifests/base/commit.yaml
manifests/base/kustomization.yaml
manifests/base/params.env
manifests/base/params.yaml

Related to: https://issues.redhat.com/browse/RHOAIENG-4345
This PR updates code-server's ImageStream object to include the new 2024a release.
**NOTE:** The updates to the code-server notebook itself will be included with the sync with upstream. 
Changes are introduced here: https://github.com/opendatahub-io/notebooks/pull/452

Update Codeserver ImageStream for the 2024a release inclusion

---

ci/check-params-env.sh

This PR updated the check-params-env test with the new changes.
(It adds checks for the new Habana as well, so failure about this is expected)
To check this localy run : `./ci/check-params-env.sh `

Fix check-params-env test with the new changes

---

cuda/rhel9-python-3.9/Dockerfile
manifests/base/cuda-rstudio-buildconfig.yaml

Update CUDA RHEL on downstream as well!
Related to: https://issues.redhat.com/browse/RHOAIENG-4374 
Tested with the PR's branch on the cluster.
CUDA build 
CUDA RStudio Build

Update cuda layer for RHEL, to 12.1

---

manifests/base/jupyter-datascience-notebook-imagestream.yaml
manifests/overlays/additional/kustomization.yaml

Remove the intel based image from the overlay as its ODH only
verify:
`kustomize build manifests/overlays/additional | grep intel`

Remove the intel based image from the overlay as its ODH only

---

jupyter/datascience/ubi8-python-3.8/Pipfile.lock
jupyter/datascience/ubi9-python-3.9/Pipfile.lock
jupyter/minimal/ubi8-python-3.8/Pipfile.lock
jupyter/minimal/ubi9-python-3.9/Pipfile.lock
jupyter/pytorch/ubi9-python-3.9/Pipfile.lock
jupyter/tensorflow/ubi9-python-3.9/Pipfile.lock
jupyter/trustyai/ubi8-python-3.8/Pipfile
jupyter/trustyai/ubi8-python-3.8/Pipfile.lock
jupyter/trustyai/ubi9-python-3.9/Pipfile
jupyter/trustyai/ubi9-python-3.9/Pipfile.lock
runtimes/datascience/ubi8-python-3.8/Pipfile.lock
runtimes/datascience/ubi9-python-3.9/Pipfile.lock
runtimes/pytorch/ubi8-python-3.8/Pipfile.lock
runtimes/pytorch/ubi9-python-3.9/Pipfile.lock
runtimes/tensorflow/ubi8-python-3.8/Pipfile.lock
runtimes/tensorflow/ubi9-python-3.9/Pipfile.lock

Related-to: 
https://issues.redhat.com/browse/RHOAIENG-4027
https://github.com/opendatahub-io/notebooks/pull/472
Manually opened the PR as the validation failed: https://github.com/red-hat-data-services/notebooks/actions/runs/8564702274

[release-2023b] sync 2023b branch with upstream 2023b branch for CVE fix.

---

rstudio/rhel9-python-3.9/Dockerfile
rstudio/rhel9-python-3.9/run-rstudio.sh

Fixes for https://issues.redhat.com/browse/RHOAIENG-3007
Changed /opt/app-root/src/Rpackages/4.3 to /opt/app-root/bin/Rpackages/4.3
Change buildconfig on cluster to uri: 'https://github.com/dibryant/notebooks'
ref: fix
Run the new build
Open new notebook
Install packages

Allow runtime script to cp the package from bin to Rpackage default path

---

.github/workflows/notebook-digest-updater.yaml
manifests/base/kustomization.yaml
manifests/base/params.env
manifests/base/params.yaml

Inconsistency for codeserver notebook parameters. There was upstream change recently that probably not got properly backported to downstream, see [1,2].
* [1] https://github.com/opendatahub-io/notebooks/pull/524
* [2] https://github.com/red-hat-data-services/notebooks/commit/ceb3dc87609af758b03a1f9e0f3f881a9af81f52
Tested locally with:
`$ kubectl kustomize manifests/base`
I'll extend our CI to run this command when anything in manifests is changed - update: opendatahub-io/notebooks#545
---
The CI failures should be fixed by:
* #179 
* #254

[fix] This fixes an inconsistency with the kustomize params

---

codeserver/ubi9-python-3.9/Dockerfile
rstudio/c9s-python-3.9/Dockerfile
rstudio/rhel9-python-3.9/Dockerfile

* [RHOAIENG-8255](https://issues.redhat.com//browse/RHOAIENG-8255): Fix spawn-fcgi-1.6.3-23.fc37.x86_64.rpm download location
Previously used location is now unavailable and returns 404 error.
This new location comes from https://koji.fedoraproject.org/koji/buildinfo?buildID=2028619
(cherry picked from commit https://github.com/red-hat-data-services/notebooks/commit/e9c3f9a977583015679c9935a5c0cbb5207280d2)
* fixup from review, use a little bit more proper rpm link
(cherry picked from commit ab0f785)
* also fix the rhel9 downstream-only build

RHOAIENG-8255: Fix spawn-fcgi-1.6.3-23.fc37.x86_64.rpm download location

---

.github/workflows/code-quality.yaml

GHA that only runs on pull_request is hard to test; I have to create PR to see it run. With this change, the action can be tested in my personal fork before I create a PR
(cherry picked from commit da7c9da3369a971a929677e06ac11c7cde595f97)

Run the static code checks on push and when manually triggered

---

amd/rhel9-python-3.9/Dockerfile
amd/rhel9-python-3.9/Pipfile
amd/rhel9-python-3.9/Pipfile.lock

Set up the rhel9 based AMD base image
This would allow the project to have RHEL based AMD base image 
for the notebook build.
Related-to: https://issues.redhat.com/browse/RHOAIENG-7501

Set up the rhel9 based AMD base image

---

rstudio/rhel9-python-3.9/Dockerfile

https://issues.redhat.com/browse/RHOAIENG-8299, https://issues.redhat.com/browse/RHOAIENG-8255, https://issues.redhat.com/browse/RHOAIENG-8740
This cherry-picks the 2023 branch changes:
* https://github.com/opendatahub-io/notebooks/pull/570
* https://github.com/opendatahub-io/notebooks/pull/571

[2023b] RHOAIENG-8299, RHOAIENG-8255, RHOAIENG-8740: Fix spawn-fcgi-1.6.3-23.fc37.x86_64.rpm and CentOS Stream 8 download locations

---

rstudio/rhel9-python-3.9/Dockerfile
rstudio/rhel9-python-3.9/run-rstudio.sh
rstudio/rhel9-python-3.9/supervisord/supervisord.conf

Related to: https://issues.redhat.com/browse/RHOAIENG-8298
Replace the `spec.source` part from rstudio-server-rhel9 Build Config with the following and press `start build` :
```
source:
type: Git
git:
uri: 'https://github.com/atheo89/notebooks'
ref: RHOAIENG-8298
```
For further info check the following [article](https://developers.redhat.com/articles/2024/06/06/how-integrate-and-use-rstudio-server-openshift-ai) 
Once the BuildConfig finish should be Completed successfully like the image bellow:
Spin Up `RStudio Server` image and ensure that is working properly:

Replace fcgi with supervisord on rstudio rhel flavor

---

.github/workflows/params-env.yaml
ci/check-params-env.sh
ci/check-runtime-images.sh
manifests/base/code-server-notebook-imagestream.yaml
manifests/base/commit.env
manifests/base/kustomization.yaml
manifests/base/params.env
manifests/base/params.yaml

This adds basic checks for the content in params.env and commit.env files with the extension of:
* https://issues.redhat.com/browse/RHOAIENG-8739
* https://issues.redhat.com/browse/RHOAIENG-7882
* https://issues.redhat.com/browse/RHOAIENG-7885
Note: this is in draft right now, since there are things that would deserved to be fixed in our code and we should discuss this:
1. there is more to backport than we expected initially (whole check-params-env.sh)
2. commit reference for code-server is wrong - this PR fixes this too, which is kind of a functional change
* part of that is that we should fix the commit reference value that we propagate for the code-server image as it is not correct now

[CI] add basic checks for params.env and commit.env files content and also runtime images check

---

manifests/base/commit.env
manifests/base/params.env

This change updates the Habana image used for the 2.10.z stream release with the bunch of updated packages where the main thing is update of the jupyter-server-proxy package [1].
* [1] https://issues.redhat.com/browse/RHOAIENG-11695
Changes between the image that is being updated: https://github.com/red-hat-data-services/notebooks/compare/cccc3b8...76a016f

[RHOAIENG-11695] Critical CVEs in jupyter-server-proxy package

---

ci/check-params-env.sh
manifests/base/commit.env
manifests/base/commit.yaml
manifests/base/jupyter-rocm-minimal-notebook-imagestream.yaml
manifests/base/jupyter-rocm-pytorch-notebook-imagestream.yaml
manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml
manifests/base/kustomization.yaml
manifests/base/params.env
manifests/base/params.yaml

Fixes for https://issues.redhat.com/browse/RHOAIENG-6447
Updated imagestream for AMD minimal pytorch and tensorflow for users that want OOTB workbench images with AMD libraries & package

[RHOAI] Updated image manifests with AMD images for minimal pytorch and tensorflow

---

.github/workflows/notebook-digest-updater.yaml
.github/workflows/runtimes-digest-updater.yaml
Makefile

This updates the digest updater GHA scripts for both regular workbench images and also runtime images.
On top of that, the runtime images GHA script was a bit enhanced and cleaned of a couple of shellcheck warnings (I can put it as a separate PR if it will be preferred).
https://issues.redhat.com/browse/RHOAIENG-12621
The relevant upstream changes are in opendatahub-io/notebooks#716.
Started relevant GHA via https://github.com/jstourac/notebooks/actions
Standard workbench images:
* https://github.com/jstourac/notebooks/actions/runs/11057100656
* Resulting PR - TBD
Runtime images:
* https://github.com/jstourac/notebooks/actions/runs/11057072140
* Resulting PR - TBD
---
The GHAs failed as we don't have any 2024b builds in https://quay.io/repository/opendatahub/workbench-images?tab=tags&tag=l …

[RHOAIENG-12621] Update the updater github action to the latest branch

---

.github/workflows/notebook-digest-updater.yaml

This contains two fixes and updates the GHA name and description slightly.
After the removal of the habana image from the set of regexps in #384,
there was kept a wrong syntax causing this part of the GHA to fail. This
change fixes this.
The regexps updated was missed as part of the #383 as there was nothing to test the GHA with before it got merged. This change should fix it making the update for the 2024b working from now on.
https://issues.redhat.com/browse/RHOAIENG-12621
---
Testing - https://github.com/jstourac/notebooks/actions/runs/11231810402
No updates detected, which I suppose is correct :slightly_smiling_face:

Fixes for the digest updater for 2024b and 2024a images releases

---

manifests/base/jupyter-habana-notebook-imagestream.yaml
manifests/base/kustomization.yaml

Fixes for https://issues.redhat.com/browse/RHOAIENG-13415 
Linking to https://github.com/red-hat-data-services/notebooks/pull/384
Reverting because we would no longer want to upgrade Habana images but continue to keep them in the manifest with removal of label so that it does not show up on UI

revert habana with removal of label opendatahub.image

---

jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json

Update runtime-image of commit 9d2af21 with codeflare-sdk changes
Follow-up: #406 
Related-to: JIRA: https://issues.redhat.com/browse/RHOAIENG-14201
This is required so that runtime images have the same codeflare-sdk upgrade.

update runtime-image of commit 9d2af21 with codeflare-sdk changes

---

.github/workflows/code-quality.yaml

Recently the kustomize test started to fail for us since the kustomize version 5.4 introduced some breaking changes for which we will need to update our manifests to be compatible. This work will be tracked in [1]. In the meantime, we should pin kustomize version in our GHA to the version that is used by the opendatahub-operator in runtime [2].
[1] https://issues.redhat.com/browse/RHOAIENG-11679
[2] https://github.com/red-hat-data-services/rhods-operator/blob/rhoai-2.12/go.mod#L30-L31
(cherry picked from commit bd8c310c358defc1151410245693488b7be78386)

[GHA] Pin kustomize version we use in our test to the particular version

---

manifests/base/jupyter-habana-notebook-imagestream.yaml

follow up for this: https://github.com/red-hat-data-services/notebooks/pull/404 
Set `opendatahub.io/notebook-image` to `false` instead of removing it completely, otherwise we confuse the operator while the reconciliation upgrade.  
Related to https://issues.redhat.com/browse/RHOAIENG-14573

Set opendatahub.io/notebook-image to false instead of removing it

---

cuda/rhel9-python-3.11/Dockerfile
cuda/rhel9-python-3.11/NGC-DL-CONTAINER-LICENSE
cuda/rhel9-python-3.11/cuda.repo-x86_64
manifests/base/cuda-rstudio-buildconfig.yaml
manifests/base/rstudio-buildconfig.yaml

Our CUDA RStudio image is based on RHEL9 with Python 3.11 image.
Unfortunatelly we missed to add this variant during our work on the
Python 3.11 addition. This change fixes it and makes the CUDA RStudio
BuildConfig work again.
* https://issues.redhat.com/browse/RHOAIENG-14585
Note: no update to https://github.com/openshift/release openshift-ci builds for this one.
---
Another change in this PR is the bump of the branch where the build config points to 2.16 one. Please, let me know if you prefer to move this to a separate PR. Also, shall we update the [base rhel9 image](https://github.com/red-hat-data-services/notebooks/pull/424/files#diff-2105488cb67dcba0fadcf8c6ce659f044ff7fc37e52eb1575cafd6ebdcba40c4R55) again? Or do we plan to do so just before the release?
---
On a cluster with a …

[RHOAIENG-14585] Add rhel9 based CUDA Python 3.11 image dockerfile

---

jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/rocm-pytorch-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/rocm-tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/tensorflow-ubi9-py39.json
jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json

Updated the runtime-images for 2024a with commit 2e29fc6
Failed: https://github.com/red-hat-data-services/notebooks/actions/runs/11748063740

Updated the runtime-images for 2024a with commit 2e29fc6

---

manifests/base/jupyter-datascience-notebook-imagestream.yaml
manifests/base/jupyter-pytorch-notebook-imagestream.yaml
manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
manifests/base/jupyter-trustyai-notebook-imagestream.yaml

Fix the Codeflare-SDK version for the 2024.1 images.
* [1] https://issues.redhat.com/browse/RHOAIENG-15710
(cherry picked from commit 9eba86551158c1890d16934e81bcba46d41876fc) (opendatahub-io/notebooks#771)

[RHOAIENG-15710] fix the version of codeflare-sdk shown for 2024.1

---

rstudio/rhel9-python-3.11/supervisord/supervisord.conf
rstudio/rhel9-python-3.9/supervisord/supervisord.conf

This is a completition change for the opendathub-io/notebooks#747 (merged into this downstream in 15952132114f926a21c5d17c99bf8b8abc50d70c). We missed these two files because we don't have rhel based images in the upstream repository.
https://issues.redhat.com/browse/RHOAIENG-14520

[RHOAIENG-14520] Change supervisord files location for rhel images

---

manifests/base/jupyter-rocm-tensorflow-notebook-imagestream.yaml

Fix the annotation for ROCm in tensorflow image
Related-to: https://issues.redhat.com/browse/RHOAIENG-13409

Fix the annotation for ROCm in tensorflow image

---

amd/rhel9-python-3.9/Pipfile
amd/rhel9-python-3.9/Pipfile.lock
base/rhel9-python-3.9/Pipfile
base/rhel9-python-3.9/Pipfile.lock

Fixes for https://issues.redhat.com/browse/RHOAIENG-16520
updating setuptools to 70.0.0 to fix a few CVEs (unable to update those pipfile.locks that are missing)

RHOAIENG-16520: update setuptools to 70.0.0 for CVE fixes

---

manifests/base/cuda-rstudio-buildconfig.yaml
manifests/base/jupyter-datascience-notebook-imagestream.yaml
manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
manifests/base/jupyter-minimal-notebook-imagestream.yaml
manifests/base/jupyter-pytorch-notebook-imagestream.yaml
manifests/base/jupyter-tensorflow-notebook-imagestream.yaml
manifests/base/jupyter-trustyai-notebook-imagestream.yaml
manifests/base/rstudio-buildconfig.yaml

https://issues.redhat.com/browse/RHOAIENG-17774
Followup to
* https://github.com/opendatahub-io/notebooks/pull/760
that applies the same change to manifests entries that are only present in red-hat-data-services/notebooks.
Previously, we used to have every json string on a single line, which meant we had long hard-to-read lines in our manifests. Now there is some human-friendly indentation in the files so it should be easier to read.
This is to nave no impact on the data stored, it is a code formatting change only.

RHOAIENG-17774: ref(manifests): add some newlines and indentation into the json strings with package version information

---

rstudio/rhel9-python-3.11/run-rstudio.sh

Move this change on RHEL9 flavor.
Related to:
https://github.com/opendatahub-io/notebooks/pull/797
https://issues.redhat.com/browse/RHOAIENG-16604

RStudio: added grabbing proxy-related env vars from container context setting them in R global env file

---

rstudio/rhel9-python-3.11/Dockerfile

Move this change on RHEL9 flavor.
Related to: 
https://github.com/opendatahub-io/notebooks/pull/798 
https://issues.redhat.com/browse/RHOAIENG-17256

RHOAIENG-17256: install necessary base OS package to make Knit rendering of R markup to PDF possible

---

ci/package_versions.py

This is forward-port of
* https://github.com/red-hat-data-services/notebooks/pull/500
Also remove outdated todos which are already done.
Here's the rendered docs in Summary
* https://github.com/red-hat-data-services/notebooks/actions/runs/13051490579?pr=501

RHOAIENG-17368: chore(release): update the package versions script with 2.16.1 support changes

---

manifests/base/jupyter-datascience-notebook-imagestream.yaml
manifests/base/jupyter-pytorch-notebook-imagestream.yaml
manifests/base/jupyter-trustyai-notebook-imagestream.yaml

This is a backport of the things relevant to the images mentioned in the KB article
* https://access.redhat.com/articles/rhoai-supported-configs
from
* https://github.com/opendatahub-io/notebooks/pull/925

[rhoai-2.18] RHOAIENG-20569: Fix the ImageStream manifests with the correct software versions

---

rstudio/rhel9-python-3.11/Dockerfile.cpu
rstudio/rhel9-python-3.11/Dockerfile.cuda
rstudio/rhel9-python-3.11/Pipfile
rstudio/rhel9-python-3.11/Pipfile.lock
rstudio/rhel9-python-3.11/kustomize/components/accelerator/kustomization.yaml
rstudio/rhel9-python-3.11/kustomize/components/accelerator/pod-patch.yaml
rstudio/rhel9-python-3.11/kustomize/overlays/accelerator/cuda/kustomization.yaml
rstudio/rhel9-python-3.11/kustomize/overlays/accelerator/cuda/pod-patch.yaml
rstudio/rhel9-python-3.11/requirements.txt

This commit is related to the ongoing work to release the `2025a` software upgrade - specific to `red-hat-data-services`.
Upgrades:
- `R`
- `4.4.1` -> `4.4.3`
- `RStudio`
- rstudio-server-rhel-2024.04.2-764-x86_64.rpm -> rstudio-server-rhel-2024.12.1-563-x86_64.rpm
A couple other "quality of life" improvements were included:
- Refactored `Dockerfile` to combine `RUN` statements where obvious/low-risk
- Better use of `ARG` references to reduce copy-pasta in `Dockerfile` instructions
- Added `kustomize` `cuda` `overlay`
Related-to: https://issues.redhat.com/browse/RHOAIENG-19484

feat(rstudio): update R/RStudio for 2025a

---

manifests/base/cuda-rstudio-buildconfig.yaml
manifests/base/rstudio-buildconfig.yaml

Manual sync to unblock https://github.com/red-hat-data-services/rhods-devops-infra/actions/runs/15137374657/job/42552299174
```
Unmerged paths:
(use "git add <file>..." to mark resolution)
both modified:   manifests/base/cuda-rstudio-buildconfig.yaml
both modified:   manifests/base/rstudio-buildconfig.yaml
```
* RStudio build configs - bump the branch reference to 2.21
(cherry picked from commit 0d294cc95343c78125a7b82deaa66d1e41e16813)
yeah we have diff between downstream and upstream on these files
rhds:
rhoai-2.20 https://github.com/red-hat-data-services/notebooks/blob/main/manifests/base/cuda-rstudio-buildconfig.yaml#L45
odh-io:
rhoai-2.21 https://github.com/opendatahub-io/notebooks/blob/main/manifests/base/cuda-rstudio-buildconfig.yaml#L45

Manual sync to unblock https://github.com/red-hat-data-services/rhods-devops-infra/actions/runs/15137374657/job/42552299174

---

.github/workflows/instant-merge.yaml

* https://issues.redhat.com/browse/RHOAIENG-26264?focusedId=27434800&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-27434800
Added PR
* https://github.com/jiridanek/notebooks/pull/12
action triggered and instamerged it
* https://github.com/jiridanek/notebooks/actions/runs/15774617408
And then the gha to update commit-latest.env also autotriggered
* https://github.com/jiridanek/notebooks/actions/runs/15774638270
So it looks like it is working.

RHOAIENG-26264: switch `GITHUB_TOKEN` to `GH_ACCESS_TOKEN` in `instant-merge.yaml` and remove unused permissions

---

manifests/base/runtime-datascience-imagestream.yaml
manifests/base/runtime-minimal-imagestream.yaml
manifests/base/runtime-pytorch-imagestream.yaml
manifests/base/runtime-rocm-pytorch-imagestream.yaml
manifests/base/runtime-rocm-tensorflow-imagestream.yaml
manifests/base/runtime-tensorflow-imagestream.yaml

Apply runtime image via the params-latest.env using kustomize
Related-to: https://issues.redhat.com/browse/RHOAIENG-28184

RHOAIENG-28184: apply runtime image via the params-latest.env using kustomize

---

manifests/base/commit-latest.env
manifests/base/params-latest.env

Update and sync rhoai-2.23 branch based the latest changes for rocm-runtime-tensorflow py312 image

Update and sync rhoai-2.23 branch based the latest changes for rocm-runtime-tensorflow py312 image

---

Makefile
rstudio/c9s-python-3.11/Dockerfile.cpu
rstudio/c9s-python-3.11/Dockerfile.cuda
rstudio/c9s-python-3.11/Pipfile
rstudio/c9s-python-3.11/Pipfile.lock
rstudio/c9s-python-3.11/requirements.txt
rstudio/rhel9-python-3.11/Dockerfile.cpu
rstudio/rhel9-python-3.11/Dockerfile.cuda
rstudio/rhel9-python-3.11/Pipfile
rstudio/rhel9-python-3.11/Pipfile.lock
rstudio/rhel9-python-3.11/requirements.txt

Running Pipfile.locks action at
* https://github.com/jiridanek/notebooks/actions/runs/16601955824
* forgot to type in branch, rerunning https://github.com/jiridanek/notebooks/actions/runs/16606301599
* https://github.com/opendatahub-io/notebooks/pull/1545

[2.22] update `setuptools` to version 78.1.1 in RStudio Pipfiles; run `dnf install` to reduce fixable base image vulnerabilities

---

codeserver/ubi9-python-3.11/Dockerfile.konflux.cpu
codeserver/ubi9-python-3.12/Dockerfile.konflux.cpu
jupyter/rocm/pytorch/ubi9-python-3.11/Dockerfile.konflux.rocm
jupyter/rocm/pytorch/ubi9-python-3.12/Dockerfile.konflux.rocm
jupyter/rocm/tensorflow/ubi9-python-3.11/Dockerfile.konflux.rocm
jupyter/tensorflow/ubi9-python-3.11/Dockerfile.konflux.cuda
jupyter/tensorflow/ubi9-python-3.12/Dockerfile.konflux.cuda
jupyter/trustyai/ubi9-python-3.11/Dockerfile.konflux.cpu
jupyter/trustyai/ubi9-python-3.12/Dockerfile.konflux.cpu
runtimes/datascience/ubi9-python-3.11/Dockerfile.konflux.cpu
runtimes/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu

This is a follow up to PR #1476, to remove more cases of the same problem.
These sections are being added by `bash ci/generate_code.sh`, so they're likely to get added back if someone runs that. If that doesn't run without changes, then the static analysis GH action will fail.

Remove more unnecessary duplicate steps

---

codeserver/ubi9-python-3.12/Dockerfile.konflux.cpu
jupyter/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu
jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.cpu
jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.cuda
jupyter/minimal/ubi9-python-3.12/Dockerfile.konflux.rocm
jupyter/pytorch+llmcompressor/ubi9-python-3.12/Dockerfile.konflux.cuda
jupyter/pytorch/ubi9-python-3.12/Dockerfile.konflux.cuda
jupyter/rocm/pytorch/ubi9-python-3.12/Dockerfile.konflux.rocm
jupyter/rocm/tensorflow/ubi9-python-3.12/Dockerfile.konflux.rocm
jupyter/tensorflow/ubi9-python-3.12/Dockerfile.konflux.cuda
jupyter/trustyai/ubi9-python-3.12/Dockerfile.konflux.cpu
runtimes/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu
runtimes/minimal/ubi9-python-3.12/Dockerfile.konflux.cpu
runtimes/pytorch+llmcompressor/ubi9-python-3.12/Dockerfile.konflux.cuda
runtimes/pytorch/ubi9-python-3.12/Dockerfile.konflux.cuda
runtimes/rocm-pytorch/ubi9-python-3.12/Dockerfile.konflux.rocm
runtimes/rocm-tensorflow/ubi9-python-3.12/Dockerfile.konflux.rocm
runtimes/tensorflow/ubi9-python-3.12/Dockerfile.konflux.cuda

Related to: https://issues.redhat.com/browse/RHAIENG-779 
Update .konflux dockerfiles to comply with ARGs

Update .konflux dockerfiles to comply with ARGs

---

jupyter/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu
jupyter/pytorch+llmcompressor/ubi9-python-3.12/Dockerfile.konflux.cuda
jupyter/pytorch/ubi9-python-3.12/Dockerfile.konflux.cuda
jupyter/rocm/pytorch/ubi9-python-3.12/Dockerfile.konflux.rocm
jupyter/rocm/tensorflow/ubi9-python-3.12/Dockerfile.konflux.rocm
jupyter/tensorflow/ubi9-python-3.12/Dockerfile.konflux.cuda
jupyter/trustyai/ubi9-python-3.12/Dockerfile.konflux.cpu

Follow up for `RHOAIENG-33169: remove MSSQL Client installation and related configurations from Dockerfiles` 
and move the changes to Dockerfile konflux variations 
Upstream PR: https://github.com/opendatahub-io/notebooks/pull/2324
Downstream sync: https://github.com/red-hat-data-services/notebooks/pull/1545/files
Related to: https://issues.redhat.com/browse/RHOAIENG-33169

follow up for RHOAIENG-33169: remove MSSQL Client installation and related configurations from Dockerfiles

---

runtimes/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu

Updating Dockerfile.konflux.cpu for runtime-datascience image.

ppc64le(runtime-datascience): sync odh-io/notebooks changes into Dockerfile.konflux.cpu

---

runtimes/datascience/ubi9-python-3.12/Dockerfile.konflux.cpu

This PR fixes the runtime-datascience build failures for s390x architecture by improving the pyarrow build configuration in Dockerfile.konflux.cpu.
Changes made:
- Added parameterized pyarrow version (17.0.0) using environment variable in /etc/profile.d/s390x.sh
- Enhanced build dependencies for s390x (added compression libraries and build tools)
- Improved CMake configuration with proper compression support
- Added proper environment variables for library paths and pkg-config
This fix follows the same pattern used for ppc64le architecture, ensuring consistency across different platforms while addressing s390x-specific requirements.
Konflux Successfull Build:- https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rhoai-tenant/applications/automation/pipelineruns/odh-pipeline- …

s390x(runtime-datascience): fix pyarrow build in Dockerfile.konflux.cpu

---

codeserver/ubi9-python-3.12/Dockerfile.konflux.cpu

replace supervisord, fcgi and supervisord with httpd on the konflux dockerfile.
upstream changes: https://github.com/opendatahub-io/notebooks/pull/2498
related to: https://issues.redhat.com/browse/RHAIENG-974

replace supervisord, fcgi and supervisord with httpd on the konflux dockerfile

---

.tekton/odh-workbench-jupyter-trustyai-cpu-py312-pull-request.yaml

https://redhat-internal.slack.com/archives/C09B6R3Q0KU/p1758551588797189?thread_ts=1757439783.679909&cid=C09B6R3Q0KU

[rhoai-2.25] cuda images should be amd64 only

---

jupyter/trustyai/ubi9-python-3.12/pylock.toml
jupyter/trustyai/ubi9-python-3.12/pyproject.toml

JIRA: https://issues.redhat.com/browse/RHOAIENG-34086
Triton here is a dependency of torch, and is just being explicitly re-declared so that the index to pull it from can be customized. Although torch was being pulled from the PyTorch index, all of its dependencies are still defaulting to coming from PyPI (or whatever default index is used for a build). In the triton case, PyPI only has x86_64 wheels for this version, but the PyTorch index has both x86_64 and aarch64 wheels, matching the arches that are available for torch.
Since it's a dependency of torch, I've also added same platform exclusion marker to omit for ppc64le.

Use triton from pytorch in trustyai image

---

jupyter/rocm/pytorch/ubi9-python-3.12/pylock.toml
jupyter/rocm/pytorch/ubi9-python-3.12/pyproject.toml
runtimes/rocm-pytorch/ubi9-python-3.12/pylock.toml
runtimes/rocm-pytorch/ubi9-python-3.12/pyproject.toml
tests/test_main.py

The 2025b upgrade should also update PyTorch ROCm package to use ROCm 6.3 instead of ROCm 6.2.4.
`make test`

Update PyTorch ROCm from version 6.2.4 to 6.3
